name: Unit Tests

on:
	push:
		branches:
			- master
  	pull_request:
		branches: [master]

jobs:
	Jest:
		runs-on: unbuntu-latest
		steps:
			- uses: actions/checkout@1
			- name: Run Tests
				run: |
					npm install
					npm test